name: 通用 Issue
description: 提交问题、需求或建议
title: "[类型]: "
labels: []
body:
  # ==================
  # 问题描述
  # ==================
  - type: markdown
    attributes:
      value: |
        感谢您提交 Issue！请详细描述您遇到的问题或需求。
        
  - type: dropdown
    id: type
    attributes:
      label: 类型
      description: 请选择最符合的类型
      options:
        - 🐛 Bug (某个功能不正常)
        - ✨ Feature (需要新功能)
        - 💡 Enhancement (改进现有功能)
        - 📝 Documentation (文档相关)
        - 🔧 Refactor (代码优化)
      default: 0
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 清晰地描述您遇到的问题或需求
      placeholder: |
        如果是 Bug：描述什么功能出了问题
        如果是 Feature：描述您想要实现什么
        如果是 Enhancement：描述当前的不便之处
    validations:
      required: true
      
  # ==================
  # 背景和动机
  # ==================
  - type: textarea
    id: context
    attributes:
      label: 背景/动机
      description: 为什么这个问题需要解决？它影响了什么？
      placeholder: |
        - 我在做什么的时候遇到这个问题
        - 这个问题导致了什么影响
        - 为什么这个功能对我很重要
    validations:
      required: true
      
  # ==================
  # 期望结果
  # ==================
  - type: textarea
    id: expected
    attributes:
      label: 期望结果
      description: 您希望看到什么样的结果？
      placeholder: |
        描述理想情况下应该是什么样的
        不需要技术方案，只需要描述效果
    validations:
      required: true
      
  # ==================
  # 当前行为（可选）
  # ==================
  - type: textarea
    id: current
    attributes:
      label: 当前行为
      description: 如果适用，描述当前的实际行为
      placeholder: |
        当前是什么样的？
        与期望有什么差距？
    validations:
      required: false
      
  # ==================
  # 重现步骤（Bug 必填）
  # ==================
  - type: textarea
    id: steps
    attributes:
      label: 重现步骤
      description: 如果是 Bug，请提供重现步骤
      placeholder: |
        1. 进入 '...' 页面
        2. 点击 '...' 按钮
        3. 输入 '...'
        4. 看到错误
    validations:
      required: false
      
  # ==================
  # 优先级评估
  # ==================
  - type: dropdown
    id: priority
    attributes:
      label: 优先级建议
      description: 您认为这个问题的优先级是？
      options:
        - 🔴 Critical (阻塞性问题，无法使用)
        - 🟠 High (严重影响使用)
        - 🟡 Medium (有影响但有替代方案)
        - 🟢 Low (体验问题，不影响使用)
      default: 2
    validations:
      required: true
      
  # ==================
  # 额外信息
  # ==================
  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 截图、日志、相关链接等
      placeholder: |
        - 相关截图
        - 错误日志
        - 参考链接
        - 环境信息（版本、系统等）
    validations:
      required: false
      
  - type: checkboxes
    id: checklist
    attributes:
      label: 检查清单
      description: 提交前请确认
      options:
        - label: 我已搜索过类似的 Issue，确认这是一个新问题
          required: true
        - label: 我已提供足够的信息来理解这个问题
          required: true
        - label: 我理解这是问题描述，具体解决方案会在后续讨论
          required: false