name: Build Desktop

on:
  workflow_dispatch:
  push:
    branches:
      - feature/client-development
    paths:
      - 'apps/desktop/**'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Build Windows
        run: |
          cd apps/desktop
          pnpm package:win
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            apps/desktop/release/*-setup.exe
            
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          
      - name: Build and Sign macOS
        run: |
          cd apps/desktop
          pnpm package:mac
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: true
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac-build-signed
          path: |
            apps/desktop/release/*.dmg