name: Documentation Management

on:
  push:
    branches:
      - 'docs/**'  # 所有 docs/ 开头的分支
      - 'doc/**'   # 或 doc/ 开头的分支
    paths:
      - 'README*.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE*'
      - 'docs/**'
      - 'assets/**'
      - '.github/**'
      - 'examples/**'
      
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'README*.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE*'
      - 'docs/**'
      - 'assets/**'
      - '.github/**'
      - 'examples/**'

jobs:
  docs-check:
    name: Documentation Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check markdown files
        run: |
          echo "📚 Documentation changes detected"
          echo "This PR contains only documentation changes and will not trigger version release"
          
      - name: Label PR as documentation
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT || github.token }}
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['documentation', 'skip-release']
            });