name: PR Merged to Develop Event

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - dev

jobs:
  trigger-release-preview:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0
          
      - name: Check for changesets
        id: check
        run: |
          # Check if there are any changesets
          CHANGESET_COUNT=0
          
          if [ -d ".changeset" ]; then
            # Count markdown files (excluding README.md)
            for file in .changeset/*.md; do
              if [ -f "$file" ] && [ "$(basename "$file")" != "README.md" ]; then
                CHANGESET_COUNT=$((CHANGESET_COUNT + 1))
              fi
            done
          fi
          
          echo "changeset_count=$CHANGESET_COUNT" >> $GITHUB_OUTPUT
          
          if [ $CHANGESET_COUNT -gt 0 ]; then
            echo "has_changesets=true" >> $GITHUB_OUTPUT
            echo "✅ Found $CHANGESET_COUNT changeset(s)"
          else
            echo "has_changesets=false" >> $GITHUB_OUTPUT
            echo "ℹ️ No changesets found"
          fi
          
      - name: Post merge notification
        uses: actions/github-script@v7
        with:
          # Use PAT_TOKEN if available for consistency
          github-token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const changesetCount = '${{ steps.check.outputs.changeset_count }}';
            const hasChangesets = '${{ steps.check.outputs.has_changesets }}' === 'true';
            
            let message = `## 🎉 Pull Request Merged!
            
            **PR #${pr.number}** has been successfully merged into \`${pr.base.ref}\`.
            `;
            
            if (hasChangesets) {
              message += `
              ### 📦 Release Status
              Found **${changesetCount} changeset(s)** ready for release.
              
              Let me show you what will be included in the next release...`;
            } else {
              message += `
              ### ℹ️ No Changesets Found
              This PR doesn't include any changesets. No version bump will occur.`;
            }
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: message
            });
            
      - name: Trigger release preview
        if: steps.check.outputs.has_changesets == 'true'
        uses: actions/github-script@v7
        with:
          # Use PAT_TOKEN if available to trigger subsequent workflows
          github-token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            
            // Wait a moment for the notification to be posted
            await new Promise(resolve => setTimeout(resolve, 1000));
            
            // Post the start release preview command
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: '/start release --preview'
            });
            
            console.log(`✅ Triggered /start release --preview for merged PR #${pr.number}`);
            
      - name: Auto-deploy dev version
        if: github.event.pull_request.merged == true
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            
            // Wait for previous operations to complete
            await new Promise(resolve => setTimeout(resolve, 2000));
            
            // Check if we should skip deployment
            const skipDeploy = pr.body && (
              pr.body.includes('[skip-deploy]') || 
              pr.body.includes('[skip-publish]')
            );
            
            if (skipDeploy) {
              console.log('⏭️ Skipping auto-deploy (found skip flag)');
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `⏭️ Auto-deployment skipped (found [skip-deploy] flag)`
              });
              return;
            }
            
            // Detect if this is a deployable project
            let deployTarget = null;
            
            // Check files changed in the PR to determine deploy target
            const { data: files } = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });
            
            const hasPackageJson = files.some(f => f.filename === 'package.json');
            const hasDockerfile = files.some(f => f.filename === 'Dockerfile');
            
            if (hasPackageJson) {
              deployTarget = 'npm';
              console.log('📦 NPM deployment target detected');
            } else if (hasDockerfile) {
              deployTarget = 'docker';
              console.log('🐳 Docker deployment target detected');
            }
            
            if (deployTarget) {
              // Trigger dev deployment
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `/deploy ${deployTarget} --tag dev --auto`
              });
              
              console.log(`✅ Triggered dev deployment for PR #${pr.number}`);
            } else {
              console.log('ℹ️ No deployable changes detected, skipping auto-deploy');
            }
            
      - name: Delete feature branch
        if: github.event.pull_request.merged == true
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const branchName = pr.head.ref;
            
            // Only delete feature/fix/docs/chore branches
            if (branchName.match(/^(feature|fix|docs|chore)\//)) {
              try {
                await github.rest.git.deleteRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `heads/${branchName}`
                });
                console.log(`✅ Deleted branch ${branchName}`);
                
                // Post comment about branch deletion
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: pr.number,
                  body: `🗑️ Branch \`${branchName}\` has been deleted.`
                });
              } catch (error) {
                console.log(`⚠️ Could not delete branch ${branchName}: ${error.message}`);
              }
            } else {
              console.log(`ℹ️ Keeping branch ${branchName} (not a feature/fix/docs/chore branch)`);
            }