name: PR Opened to Develop Event

on:
  pull_request:
    types: [opened]
    branches:
      - develop
      - dev

jobs:
  trigger-auto-changeset:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      
    steps:
      - name: Check if changeset should be created
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            
            // Skip if PR is from a bot
            if (pr.user.type === 'Bot' || pr.user.login.includes('[bot]')) {
              console.log('Skipping: PR is from a bot');
              core.setOutput('should_trigger', 'false');
              return;
            }
            
            // Skip if PR is a draft
            if (pr.draft) {
              console.log('Skipping: PR is a draft');
              core.setOutput('should_trigger', 'false');
              return;
            }
            
            // Skip if title indicates WIP
            if (pr.title.toLowerCase().includes('wip') || pr.title.toLowerCase().includes('work in progress')) {
              console.log('Skipping: PR is marked as WIP');
              core.setOutput('should_trigger', 'false');
              return;
            }
            
            // Already filtered by GitHub event configuration
            const targetBranch = pr.base.ref;
            console.log(`Target branch: ${targetBranch}`);
            
            core.setOutput('should_trigger', 'true');
            core.setOutput('pr_number', pr.number);
            core.setOutput('pr_title', pr.title);
            core.setOutput('target_branch', targetBranch);
            
      - name: Post automation notice
        if: steps.check.outputs.should_trigger == 'true'
        uses: actions/github-script@v7
        with:
          # Use PAT_TOKEN if available to trigger subsequent workflows
          github-token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = ${{ steps.check.outputs.pr_number }};
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `🤖 **Automated Workflow Triggered**
              
              I've detected a new pull request targeting \`${{ steps.check.outputs.target_branch }}\`.
              
              Let me analyze your commits to determine the appropriate version bump...`
            });
            
      - name: Trigger changeset command
        if: steps.check.outputs.should_trigger == 'true'
        uses: actions/github-script@v7
        with:
          # Use PAT_TOKEN if available to trigger subsequent workflows
          github-token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = ${{ steps.check.outputs.pr_number }};
            
            // Wait a moment for the notice to be posted
            await new Promise(resolve => setTimeout(resolve, 1000));
            
            // Post the actual command
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: '/changeset --auto'
            });
            
            console.log(`✅ Triggered /changeset --auto for PR #${prNumber}`);