name: PR Opened to Main Event

on:
  pull_request:
    types: [opened]
    branches:
      - main
      - master

jobs:
  trigger-beta-release:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      
    steps:
      - name: Check if release PR
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            
            // Skip if PR is from a bot (unless it's github-actions or a release bot)
            if (pr.user.type === 'Bot' && 
                !pr.user.login.includes('github-actions') && 
                !pr.user.login.includes('release')) {
              console.log('Skipping: PR is from a non-release bot');
              core.setOutput('should_trigger', 'false');
              return;
            }
            
            // Skip if PR is a draft
            if (pr.draft) {
              console.log('Skipping: PR is a draft');
              core.setOutput('should_trigger', 'false');
              return;
            }
            
            // Check if it's a release PR (from release/* branch)
            const sourceBranch = pr.head.ref;
            const isReleaseBranch = sourceBranch.startsWith('release/') || 
                                   sourceBranch.startsWith('hotfix/');
            
            if (!isReleaseBranch) {
              console.log(`Skipping: Not a release branch (${sourceBranch})`);
              core.setOutput('should_trigger', 'false');
              return;
            }
            
            core.setOutput('should_trigger', 'true');
            core.setOutput('pr_number', pr.number);
            core.setOutput('pr_title', pr.title);
            core.setOutput('source_branch', sourceBranch);
            
      - name: Post automation notice
        if: steps.check.outputs.should_trigger == 'true'
        uses: actions/github-script@v7
        with:
          # Use PAT_TOKEN if available to trigger subsequent workflows
          github-token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = ${{ steps.check.outputs.pr_number }};
            const sourceBranch = '${{ steps.check.outputs.source_branch }}';
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `🤖 **Release Automation Triggered**
              
              I've detected a release PR from \`${sourceBranch}\` to \`main\`.
              
              Let me create a beta release for testing...`
            });
            
      - name: Trigger beta release command
        if: steps.check.outputs.should_trigger == 'true'
        uses: actions/github-script@v7
        with:
          # Use PAT_TOKEN if available to trigger subsequent workflows
          github-token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = ${{ steps.check.outputs.pr_number }};
            
            // Wait a moment for the notice to be posted
            await new Promise(resolve => setTimeout(resolve, 1000));
            
            // Post the beta release command
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: '/release --prerelease beta'
            });
            
            console.log(`✅ Triggered /release --prerelease beta for PR #${prNumber}`);