name: Build Desktop Apps

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build all packages
        run: pnpm build

      - name: Build macOS app
        working-directory: apps/desktop
        run: pnpm package:mac

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            apps/desktop/*.dmg
            apps/desktop/*.zip
          if-no-files-found: warn

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build all packages
        run: pnpm build

      - name: Build Windows app
        working-directory: apps/desktop
        run: pnpm package:win

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            apps/desktop/*.exe
            apps/desktop/*.nsis
            apps/desktop/*.msi
          if-no-files-found: warn

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Build all packages
        run: pnpm build

      - name: Build Linux app
        working-directory: apps/desktop
        run: pnpm package:linux

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            apps/desktop/*.AppImage
            apps/desktop/*.deb
            apps/desktop/*.rpm
            apps/desktop/*.snap
          if-no-files-found: warn

  upload-release:
    name: Upload to Release
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            macos-build/*.dmg
            windows-build/*.exe
            linux-build/*.AppImage
            linux-build/*.deb
            linux-build/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}