name: Build Desktop Apps

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Configure git for HTTPS
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://".insteadOf "ssh://"

      - name: Install dependencies
        run: pnpm install

      - name: Build all packages
        run: pnpm build

      - name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}

      - name: Build macOS app
        working-directory: apps/desktop
        run: |
          echo "Building macOS versions..."
          pnpm build
          npx electron-builder --mac --x64 --arm64
        env:
          CSC_LINK: ${{ secrets.MACOS_CERTIFICATE }}
          CSC_KEY_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          CSC_IDENTITY_AUTO_DISCOVERY: true

      - name: Notarize macOS DMG
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: apps/desktop
        run: |
          # Check if Apple credentials are available
          if [[ -z "${{ secrets.APPLE_ID }}" ]] || \
             [[ -z "${{ secrets.APPLE_ID_PASSWORD }}" ]] || \
             [[ -z "${{ secrets.APPLE_TEAM_ID }}" ]]; then
            echo "⚠️ Skipping notarization: Missing Apple credentials"
            echo "To enable notarization, please set APPLE_ID, APPLE_ID_PASSWORD, and APPLE_TEAM_ID secrets"
            exit 0
          fi
          
          echo "📝 Starting notarization process..."
          
          # Notarize each DMG file
          for dmg in release/*.dmg; do
            if [ -f "$dmg" ]; then
              echo "Notarizing $(basename $dmg)..."
              
              # Submit for notarization and wait for completion
              xcrun notarytool submit "$dmg" \
                --apple-id "${{ secrets.APPLE_ID }}" \
                --password "${{ secrets.APPLE_ID_PASSWORD }}" \
                --team-id "${{ secrets.APPLE_TEAM_ID }}" \
                --wait \
                --timeout 1200
              
              # Staple the notarization ticket to the DMG
              xcrun stapler staple "$dmg"
              
              echo "✅ Successfully notarized $(basename $dmg)"
            fi
          done
          
          echo "✅ Notarization process completed"

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            apps/desktop/release/*.dmg
            apps/desktop/release/latest-mac.yml
          if-no-files-found: warn

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Configure git for HTTPS
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://".insteadOf "ssh://"

      - name: Install dependencies
        run: pnpm install

      - name: Build all packages
        run: pnpm build

      - name: Build Windows app
        working-directory: apps/desktop
        run: |
          pnpm build
          npx electron-builder --win

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            apps/desktop/release/*setup*.exe
            apps/desktop/release/latest.yml
          if-no-files-found: warn

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Configure git for HTTPS
        run: |
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          git config --global url."https://".insteadOf "ssh://"

      - name: Install dependencies
        run: pnpm install

      - name: Build all packages
        run: pnpm build

      - name: Build Linux app
        working-directory: apps/desktop
        run: |
          pnpm build
          npx electron-builder --linux

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            apps/desktop/release/*.rpm
            apps/desktop/release/latest-linux.yml
          if-no-files-found: warn

  upload-release:
    name: Upload to Release
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            macos-build/*.dmg
            macos-build/latest-mac.yml
            windows-build/*setup*.exe
            windows-build/latest.yml
            linux-build/*.rpm
            linux-build/latest-linux.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}