name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'
      branch:
        type: string
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Node environment
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ inputs.node-version }}

      - name: Lint code
        run: pnpm lint

      - name: Run tests
        run: |
          pnpm test:unit
          pnpm test:integration
          pnpm test:examples