name: Sync Workflows Simple

on:
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT || github.token }}
          
      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Sync to test branch
        run: |
          echo "Syncing to test branch..."
          git fetch origin test
          git checkout test
          git checkout develop -- .github/workflows/
          
          if ! git diff --quiet; then
            git add .github/workflows/
            git commit -m "chore: sync workflows from develop"
            git push origin test
            echo "✅ Synced to test"
          else
            echo "ℹ️ No changes to sync"
          fi
          
      - name: Create summary
        if: always()
        run: |
          echo "## Workflow Sync Result" >> $GITHUB_STEP_SUMMARY
          echo "- Source: develop" >> $GITHUB_STEP_SUMMARY
          echo "- Target: test" >> $GITHUB_STEP_SUMMARY
          echo "- Status: Complete" >> $GITHUB_STEP_SUMMARY